CREATE DATABASE SNOWFLAKE_ASSIGNMENT;
CREATE SCHEMA SNOWFLAKE_ASSIGNMENT.ASSIGNMENT_SCHEMA;
USE DATABASE SNOWFLAKE_ASSIGNMENT;
USE SCHEMA ASSIGNMENT_SCHEMA;
SELECT
    CURRENT_DATABASE() AS CURRENT_DATABASE,
    CURRENT_SCHEMA() AS CURRENT_SCHEMA;
    
